//
// Copyright (C) 2026 Intel Corporation.
// SPDX-License-Identifier: Apache-2.0
//

#pragma once

#include <algorithm>
#include <iostream>
#include <string_view>
#include <unordered_map>

#include "vpux_elf/accessor.hpp"
#include "vpux_elf/reader.hpp"
#include "vpux_elf/types/elf_structs.hpp"
#include "vpux_elf/types/section_header.hpp"

// Class which encapsulates a group of memory requirements generated by ELF sections filtered based on a given criteria
// The actual memory requirement is stored within the elf::SectionHeader sh_size field
struct MemoryRequirementsGroup {
    struct IndividualRequirement {
        size_t _index;
        elf::SectionHeader _header;
    };
    // Track individual sections that generated requirements
    std::vector<IndividualRequirement> _individualRequirements = {};
    // Track total required memory
    size_t _totalGroupRequirement = 0;
};

using MemoryRequirementsMap = std::unordered_map<std::string, MemoryRequirementsGroup>;
std::vector<const std::pair<const std::string, MemoryRequirementsGroup>*> getSortedRequirements(
        const MemoryRequirementsMap& memoryReqMap);

// Class which encapsulates memory requirements for an arbitrary collection of groups
class MemoryRequirementsCategory {
public:
    MemoryRequirementsCategory(std::string_view name);

    void addRequirementToGroup(const std::string& groupName,
                               MemoryRequirementsGroup::IndividualRequirement& individualRequirement);

    size_t getTotalRequired() const;

    void print();

private:
    MemoryRequirementsMap _map = {};
    std::string _name = {};
    size_t _total = 0;
};

using ProcessorMap = std::unordered_map<std::string, elf::Elf_Xword>;
const ProcessorMap& getDefaultProcessorMap();

// Class which scans a given blob and stores memory requirements information based the following categories:
//  - processor type
//  - allocation type
class BlobScanner {
public:
    using Requirement = MemoryRequirementsGroup::IndividualRequirement;

    BlobScanner(elf::AccessManager* accessManager, const ProcessorMap& processorMap);

    const MemoryRequirementsCategory& getRequirementsByProcessor();

    const MemoryRequirementsCategory& getRequirementsByAllocationType();

    void printResult();

private:
    MemoryRequirementsCategory _processorRequirements;
    MemoryRequirementsCategory _allocationTypeRequirements;
};
