#
# Copyright (C) 2022-2026 Intel Corporation.
# SPDX-License-Identifier: Apache-2.0
#

add_subdirectory(example)
add_subdirectory(accessor)
add_subdirectory(helpers)
add_subdirectory(hpi)
add_subdirectory(loader)
add_subdirectory(managed_buffer)
add_subdirectory(reader)
add_subdirectory(relocations)
add_subdirectory(serial_struct_base)
add_subdirectory(writer)
